name: Build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/imilchev/go-devcontainer:v1.1.0
    steps:
      - uses: actions/checkout@v2

      - name: Lint
        run: task lint

      - name: Build
        run: task build