name: Build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/imilchev/go-devcontainer:1.17.5
    steps:
      - uses: actions/checkout@v2

      - name: Lint
        run: task lint

      - name: Build
        run: task build

      - name: Test
        run: task test

      - name: Upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: unit-test-coverage
          path: output/coverage.html